import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = localFont({
  src: '../../public/fonts/lovable.woff2', // Path to your font file
  weight: '400', // Font weight
  style: 'normal', // Font style
  variable: '--font-default', // Defines the CSS variable
})

// const myDefaultFont = localFont({
//   src: '../../public/fonts/lovable.woff2', // Path to your font file
//   weight: '400', // Font weight
//   style: 'normal', // Font style
//   variable: '--font-default', // Defines the CSS variable
// });

export const metadata = {
  title: "Lovable - Your Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} ${myDefaultFont.variable} h-full antialiased`}
      className={`${myFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
